""" top level run script """

import argparse
import json
import os
import shutil
import logging
import glob
from pathlib import Path
from typing import List, Dict

from aind_data_schema.core.quality_control import QualityControl, QCMetric


def recreate_file_structure(
    input_dir: str, output_dir: str, excluded_file: str
) -> None:
    """Recreate the original file structure with subfolders while moving files."""

    def ignore_qc_files(dir, files):
        qc_files = {
            os.path.basename(f)
            for f in glob.glob(os.path.join(dir, "*quality_control*.json"))
        }
        return qc_files

    # Copy all files from input_dir to output_dir (excluding directories)
    for file_name in os.listdir(input_dir):
        source_path = os.path.join(input_dir, file_name)
        destination_path = os.path.join(output_dir, file_name)

        if os.path.isfile(source_path) and file_name != excluded_file:
            shutil.copy(source_path, destination_path)

    for folder_name in os.listdir(input_dir):
        source_folder = os.path.join(input_dir, folder_name)
        destination_folder = os.path.join(output_dir, folder_name)
        if os.path.isdir(source_folder):  # Only copy directories
            shutil.copytree(source_folder, destination_folder, ignore=ignore_qc_files)


def find_quality_control_jsons(data_folder: str, path_string: str) -> List:
    """Find all '{path_string}.json' files in the given folder and subfolders."""
    data_path = Path(data_folder)
    json_files = list(data_path.rglob(f"*{path_string}*.json"))

    """
    Please note that your reference paths should be in ref
    To the asset generated by the Pipeline, not your
    results folder. Check pipeline connections to validate
    """
    json_list = []
    for file in json_files:
        with open(file, "r") as f:
            json_list.append(json.load(f))

    return json_list


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments
    """
    parser = argparse.ArgumentParser(description="QCEvaluation Aggregator")

    parser.add_argument(
        "--input_dir", type=str, default="/data", help="Input directory"
    )

    parser.add_argument(
        "--output_dir", type=str, default="/results", help="Output directory"
    )

    parser.add_argument(
        "--notes", type=str, help="Notes",
    )

    return parser.parse_args()


def run() -> None:
    """
    This function finds all files in the input directory with name like
    '*evaluation.json'. It deserializes each into an aind-data-schema
    QCEvaluation objects, then creates a single quality_control.json file.
    """

    args = parse_args()
    input_dir = args.input_dir
    output_dir = args.output_dir
    notes = args.notes

    # In the event that people are using metric jsons we can merge
    metric_jsons = find_quality_control_jsons(input_dir, "metric")

    metrics = []
    for metric in metric_jsons:
        metrics.append(QCMetric.model_validate(metric))

    # Handle merging for quality_control jsons instead
    qc_jsons = find_quality_control_jsons(input_dir, "quality_control")
    qcs = []
    default_grouping = ["modality", []]

    for current_qc in qc_jsons:
        current_qc_model = QualityControl.model_validate(current_qc)
        for metric in current_qc_model.metrics:
            qcs.append(QCMetric.model_validate(metric))
        
        for idx, grouping in enumerate(current_qc_model.default_grouping):
            if idx == 0:
                continue

            if isinstance(grouping, tuple):
                for group in grouping:
                    default_grouping[1].append(group)
            else:
                default_grouping[1].append(grouping)

    qc = QualityControl(metrics=qcs, default_grouping=default_grouping)

    qc.write_standard_file(output_dir)

    """
    We'd like to have our files organized such that QC is in the
    results directory while plots are in a named folder.
    This allows the final results asset to have the same structure
    We need to generate QC in the parent to ensure it works with the
    Web portal
    """
    excluded_file = "quality_control.json"

    # We want to recreate input file struct
    recreate_file_structure(input_dir, output_dir, excluded_file)


if __name__ == "__main__":
    run()