#!/usr/bin/env bash
set -ex

ls
ls /data

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

python -u run_capsule.py "$@" 2>&1 | tee -a /results/capsule_output.log