#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

pip list 2>&1 | tee -a /results/pip_list.log

python -u run_capsule.py --input_dir /scratch/data/ --output_dir /results/ --temp_dir /scratch/temp/ --debug True 2>&1 | tee -a /results/capsule_output.log