#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

pip list 2>&1 | tee -a /results/pip_list.log

# python -u run_capsule.py  --debug True --input_dir /data/multiplane-ophys_839909_2026-02-26_15-11-01_v2/ --output_dir /results/ --temp_dir /scratch/temp/ 2>&1 | tee -a /results/capsule_output.log
python -u run_capsule.py  --debug True --input_dir /data/single-plane-ophys_767715_2025-07-25_17-40-22_v2/ --output_dir /results/ --temp_dir /scratch/temp/ 2>&1 | tee -a /results/capsule_output.log