#!/usr/bin/env bash
set -e

cd /
git clone https://github.com/AllenNeuralDynamics/aind-pophys-converter.git
cd aind-pophys-converter
# Checkout feature branch with TIFF iteration optimizations
git checkout feat/tiff-iteration-optimization || git checkout main
pip install -e .
git pull